import {schoolPeriods} from './attendanceReport.js';
export const reportPeriods = [...schoolPeriods,['Full year','2026-09-01','2027-06-30']];
export const beijingToday = () => new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function reportMark(course) {return course.mark_override!=='' && course.mark_override!=null ? Number(course.mark_override) : course.calculated_mark;}
export function reportCardHtml(cards, settings) {
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const statuses=['Present','Absent','Late','Excused','Unrecorded'];
 return `<!doctype html><html><head><title>Student report cards</title><style>@page{size:A4 portrait;margin:14mm}body{font:12px Arial;color:#111;line-height:1.4}h1{font-size:24px}h2{font-size:16px}table{border-collapse:collapse;width:100%;margin:12px 0}th,td{border:1px solid #aaa;padding:7px;text-align:left;vertical-align:top}tr{break-inside:avoid}thead{display:table-header-group}.card{break-after:page}.card:last-child{break-after:auto}.comment{white-space:pre-wrap}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px}.note{font-size:10px;color:#444}@media print{button{display:none}}</style></head><body><button onclick="window.print()">Print / Save PDF</button>${cards.map(card=>{const config=card.config||settings.config;const date=card.report_date||settings.report_date;return `<section class="card"><h1>${esc(config.type)} Report Card</h1><p>${esc(card.school_name||settings.school_name||'Super LMS')} · ${esc(card.class_title||settings.class_title)}</p><div class="meta">${[['Student',card.student_name],['Student ID',card.student_id],['PEN',card.pen],['Email',card.student_email],['Grade',card.student_grade],['Class',card.student_class],['Reporting period',config.start+' to '+config.end],['Report date',date]].map(([k,v])=>`<div><strong>${k}:</strong> ${esc(v||'Not recorded')}</div>`).join('')}</div><h2>Grades and teacher comments</h2><table><thead><tr><th>Course</th><th>Mark</th><th>Comments</th></tr></thead><tbody>${card.courses.map(c=>`<tr><td>${esc(c.title)}<br><span class="note">${c.graded_count} of ${c.assignment_count} assignments graded</span></td><td>${reportMark(c)==null?'Not graded':esc(reportMark(c))+'%'}</td><td class="comment">${esc([c.com1,c.com2].filter(Boolean).join('\n\n'))}</td></tr>`).join('')}</tbody></table><h2>Attendance by course</h2><table><thead><tr><th>Course</th>${statuses.map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${card.courses.map(c=>`<tr><td>${esc(c.title)}</td>${statuses.map(s=>`<td>${esc(c.attendance[s])}</td>`).join('')}</tr>`).join('')}</tbody></table><p class="note">Attendance counts saved class sessions in the reporting period. Unrecorded entries are not absences. Counts are shown by course because multiple classes may meet on the same day.</p><p class="note">Grade basis: ${config.gradeBasis==='cumulative'?'all dated assignments through the period end':'assignments dated within the reporting period'}. Assignment dates use Beijing time. Blank or ungraded scores are excluded. Report mark adjustments do not change the gradebook.</p></section>`;}).join('')}</body></html>`;
}
