const {test}=require('node:test');const assert=require('node:assert/strict');const express=require('express');const jwt=require('jsonwebtoken');const {createQuizzesRouter}=require('./quizzes');const {validateQuiz,publicQuestions,markQuiz,validateMarks}=require('../quizGrading');const {publishGradebook,linkGradebook}=require('../quizGradebook');
const id='7bf2cac4-32e1-4c94-b60b-d2f297b11f83';const qs=validateQuiz({title:'Quiz',questions:[{id:'q',title:'Which?',type:'Multiple Choice',required:true,options:['A','B'],points:2,answerKey:'B'},{id:'essay',title:'Explain',type:'Essay',required:true,points:3}]});
const student={name:'Learner',email:'learner@example.com',grade:'10',class:'10A',gender:'Female'};
const auth=(role,userId=4)=>({Authorization:'Bearer '+jwt.sign({id:userId,role},process.env.JWT_SECRET||'super-lms-development-secret-change-before-production')});
async function server(fn){const writes=[];const pool={query:async(sql,args)=>{if(sql.startsWith('SELECT NULLIF'))return {rows:[{school_id:12}]};if(sql.includes("FROM users u WHERE id="))return {rows:[{id:4,email:student.email,school_id:12}]};if(sql.includes("status='open'"))return {rows:args[0]===id?[{id,school_id:12,questions:JSON.stringify(qs),status:'open',title:'Quiz'}]:[]};if(sql.startsWith('SELECT * FROM teacher_quizzes')||sql.startsWith('SELECT r.* FROM teacher_quiz_responses r JOIN')){assert.ok(sql.includes('author_id=$2'));assert.equal(args[1],4);return {rows:[]}}if(sql.startsWith('UPDATE teacher_quizzes')){assert.ok(sql.includes('author_id=$4'));assert.equal(args[3],4);return {rows:[]}}if(sql.startsWith('INSERT'))writes.push({sql,args});return {rows:[]}},connect:async()=>({query:(...args)=>pool.query(...args),release(){}})};const app=express();app.use(express.json());app.use('/api/quizzes',createQuizzesRouter(pool));const s=await new Promise((resolve,reject)=>{const server=app.listen(0,'127.0.0.1',()=>resolve(server));server.on('error',reject)});try{await fn('http://127.0.0.1:'+s.address().port,writes)}finally{await new Promise(r=>s.close(r))}}
test('quiz answer keys are private, and teacher listings and status writes are owner scoped',()=>server(async base=>{const quiz=await(await fetch(base+'/api/quizzes/studio?survey='+id)).json();assert.ok(JSON.parse(quiz.questions).every(q=>!Object.hasOwn(q,'answerKey')));assert.equal((await fetch(base+'/api/quizzes/studio',{headers:auth('teacher')})).status,200);assert.equal((await fetch(base+'/api/quizzes/studio',{headers:auth('student')})).status,403);const r=await fetch(base+'/api/quizzes/studio',{method:'POST',headers:{...auth('teacher'),'Content-Type':'application/json'},body:JSON.stringify({action:'status',id,status:'open'})});assert.equal(r.status,404)}));
test('quiz submissions require a student account, ignore typed email and score tampering, and retain original keys privately',()=>server(async(base,writes)=>{const body={action:'submit',surveyId:id,student:{...student,email:'other@example.com'},answers:{q:'B',essay:'Explanation'},marks:[{score:100}]};const send=headers=>fetch(base+'/api/quizzes/studio',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});assert.equal((await send({})).status,401);assert.equal((await send(auth('teacher'))).status,403);assert.equal((await send(auth('student'))).status,200);assert.equal(writes.length,1);assert.equal(JSON.parse(writes[0].args[2]).email,student.email);assert.equal(writes[0].args[6],4);const marks=JSON.parse(writes[0].args[5]);assert.equal(marks[0].score,2);assert.equal(marks[1].score,null);assert.equal(JSON.parse(writes[0].args[4])[0].answerKey,'B')}));
test('grading validates answer keys, array answers, and score limits',()=>{assert.equal(publicQuestions(qs)[0].answerKey,undefined);assert.deepEqual(markQuiz(qs,{q:'A',essay:'Good'}).map(m=>m.score),[0,null]);assert.throws(()=>validateMarks([{id:'q',score:3},{id:'essay',score:2}],qs),/score/);assert.throws(()=>validateMarks([{id:'q',score:1},{id:'essay',score:null}],qs),/score/);assert.throws(()=>validateQuiz({title:'Quiz',questions:[{...qs[0],answerKey:'X'}]}),/correct answer/)});
const req={user:{id:4},schoolId:12};
const quiz={id,title:'Quiz',questions:JSON.stringify(qs),course_id:8,assignment_id:9};
const response={id,student_user_id:7,questions:JSON.stringify(qs),student:JSON.stringify(student),answers:JSON.stringify({q:'B',essay:'Essay'}),marks:JSON.stringify([{id:'q',points:2,score:2},{id:'essay',points:3,score:2}])};
function gradeClient({enrolled=true,existing=false,pending=false,owned=true}={}){const writes=[];return {writes,query:async(sql,args)=>{if(sql.startsWith('SELECT * FROM teacher_quizzes')){assert.match(sql,/author_id=\$2/);return {rows:owned?[quiz]:[]}}if(sql.startsWith('SELECT c.id')){assert.match(sql,/teacher_id=\$2/);return {rows:[{id:8,content_id:2}]}}if(sql.startsWith('SELECT id FROM assignments'))return {rows:[{id:9}]};if(sql.startsWith('SELECT * FROM teacher_quiz_responses'))return {rows:[pending?{...response,marks:JSON.stringify([{id:'q',score:2},{id:'essay',score:null}])}:response]};if(sql.startsWith('SELECT u.id')){assert.equal(args[1],7);return {rows:enrolled?[{id:7,name:'Learner',email:student.email}]:[]}}if(sql.startsWith('SELECT submission_id'))return {rows:existing?[{submission_id:10}]:[]};if(sql.startsWith('INSERT')||sql.startsWith('UPDATE')){writes.push({sql,args});return {rows:[{id:10}]}}return {rows:[]}}}}
test('gradebook publishing matches the authenticated roster account and uses existing direct-percentage marks',async()=>{const client=gradeClient();const result=await publishGradebook(client,req,{id,responseIds:[id]});assert.equal(result.published[0].percent,80);const write=client.writes.find(w=>w.sql.startsWith('INSERT INTO submissions'));assert.equal(write.args[4],7);assert.equal(write.args[8],80);assert.equal(write.args[11].directPercentage,true);assert.equal(write.args[11].pointsEarned,4)});
test('repeat publishing updates the mapped submission; unmarked, unenrolled, or foreign quizzes cannot publish',async()=>{const client=gradeClient({existing:true});await publishGradebook(client,req,{id,responseIds:[id]});assert.ok(client.writes.some(w=>w.sql.startsWith('UPDATE submissions')));assert.ok(!client.writes.some(w=>w.sql.startsWith('INSERT INTO submissions')));for(const options of [{pending:true},{enrolled:false}]){const c=gradeClient(options);const result=await publishGradebook(c,req,{id,responseIds:[id]});assert.equal(result.published.length,0);assert.equal(c.writes.length,0)}const other=gradeClient({owned:false});await assert.rejects(()=>publishGradebook(other,req,{id,responseIds:[id]}));assert.equal(other.writes.length,0)});
test('linking an already linked quiz cannot create a duplicate gradebook assignment',async()=>{const client=gradeClient();await assert.rejects(()=>linkGradebook(client,req,{id,courseId:8,subcategoryId:2}),/already/);assert.equal(client.writes.length,0)});
test('gradebook linking uses the course content and validates its grading subcategory',async()=>{const writes=[];const client={query:async(sql,args)=>{if(sql.startsWith('SELECT * FROM teacher_quizzes'))return {rows:[{...quiz,assignment_id:null}]};if(sql.startsWith('SELECT c.id'))return {rows:[{id:8,content_id:2}]};if(sql.startsWith('SELECT cs.id')){assert.equal(args[1],2);assert.match(sql,/course_category_id/);return {rows:[{id:6}]}}if(sql.startsWith('INSERT INTO assignments')){writes.push({sql,args});return {rows:[{id:9}]}}if(sql.startsWith('UPDATE teacher_quizzes')){writes.push({sql,args});return {rows:[]}}throw Error('Unexpected query')}};assert.deepEqual(await linkGradebook(client,req,{id,courseId:8,subcategoryId:6}),{assignmentId:9,courseId:8});assert.equal(writes[0].args[0],2);assert.equal(writes[0].args[4],5);assert.equal(writes[1].args[0],8)});
